# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

set -g @plugin 'nhdaly/tmux-better-mouse-mode'

set-option -g mouse on
set-option -g focus-events on
set-option -a terminal-features 'tmux-256color:RGB'

# Toggle between narrow and wide pane
bind-key T run-shell "if [ $(tmux display-message -p '#{pane_width}') -lt 100 ]; then tmux resize-pane -x 120; else tmux resize-pane -x 80; fi"

run '~/.tmux/plugins/tpm/tpm'
